vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        carousels:
            uri_prefix: /images/carousels
            upload_destination: '%kernel.project_dir%/public/images/carousels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
